WepAppEmpty/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WepAppEmpty.Models
{
    public class Contact
    {
        public int Id { get; set; }

        public string LastName { get; set; }
 
        public string FirstName { get; set; }

        public string Email { get; set; }
     
        public int CategoryId { get; set; }

    }
}

WepAppEmpty/Controllers/ContactController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Model.Client;
using Model.Client.Data;
using Model.Client.Repositories;
using Model.Client.Services;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WepAppEmpty.Infracstructures.Security;
using WepAppEmpty.Infracstructures.Sessions;
using WepAppEmpty.Models;
using WepAppEmpty.Models.Forms;

namespace WepAppEmpty.Controllers
{
    [AuthRequired]//LE AuthRequired va me permettre de ne plus faire le test à chaque fois pour savoir si je suis authentifié au par car la classe AuthRequired le fait déjà
    public class ContactController : Controller
    {
        private readonly ISessionManager _sessionManager;
        private readonly IContactRepository _contactRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IAuthRepository _authRepository;

        public ContactController(IContactRepository contactService, ICategoryRepository categoryService, IAuthRepository authRepository, ISessionManager sessionManager)
        {
            _contactRepository = contactService;
            _categoryRepository = categoryService;
            _authRepository = authRepository;
            _sessionManager = sessionManager;
        }

        public IActionResult Index()
        {

            Dictionary<string, IEnumerable<Contact>> allContacts = new Dictionary<string, IEnumerable<Contact>>();

            foreach(Category category in _categoryRepository.Get())
            {
                var contacts = _authRepository.getContactsByCategoryAndUser(_sessionManager.User.Id, category.Id);
                allContacts.Add(category.Name, contacts);
            }

            return View(allContacts);
        }
    
        public IActionResult Details(int id)
        {
            return View(_contactRepository.Get(id));
        }
        //J'ai besoin de deux methode create, la première c'est en get pour recuperer mon formulaire au server et l'afficher
        //La deuxième, c'est pour envoyer mon formulaire avec les données remplies. Elle contient l'attribut httpPost
        public IActionResult Create(int id)
        {
            CreateContactForm form = new CreateContactForm();

            //On ne peut pas envoyé directement les catégorie qu'on récupère ans la base de données à la vue
            //puisque ce que la vue doit affichée, ce sont des selectedItems
            form.Categories = GetCategories();

            if (id != 0)
            {
                Contact contact = _contactRepository.Get(id);

                if (contact is null)
                    return RedirectToAction("Index");

                //EditContactForm form = new EditContactForm();
                form.Id = contact.Id;
                form.LastName = contact.LastName;
                form.FirstName = contact.FirstName;
                form.Email = contact.Email;
                form.CategoryId = contact.CategoryId;
            }

            return View(form);
        }

        //Les paramètres de la methode create en post doivent avoir les mêmes nom que la valeur de name dans le formulaire independamment de la casse
        [HttpPost]
        public IActionResult Create(CreateContactForm form)
        {
            //ValidationContext validationContext = new ValidationContext(form);
            //if (!ModelState.IsValid && form.Validate(validationContext).Count() != 0)
            if (!ModelState.IsValid)
            {
                form.Categories = GetCategories();
                return View(form);
            }

            if(form.Id == 0)
            {
                Contact newcontact = new Contact(form.LastName, form.FirstName, form.Email, form.CategoryId, _sessionManager.User.Id);

                _contactRepository.Insert(newcontact);
            } 
            else
            {
                Contact contact = _contactRepository.Get(form.Id);
                contact.LastName = form.LastName;
                contact.FirstName = form.FirstName;
                if (contact.Email != form.Email)
                {
                    contact.Email = form.Email;
                }
                contact.CategoryId = form.CategoryId;

                _contactRepository.Update(form.Id, contact);
            }

            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            Contact contact = _contactRepository.Get(id);

            if (contact is null)
                return RedirectToAction("Index");
            //_contactService.DeleteContact(id);

            return View(contact);
        }

        [HttpPost]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            _contactRepository.Delete(id);

            return RedirectToAction("Index");
        }

        private IEnumerable<SelectListItem> GetCategories()
        {
            IEnumerable<Category> categories = _categoryRepository.Get();

            //Je récupère mes catégories de ma base de données que je transforme en selected items
            //qui seront envoyé à mon formulaire dans le select
            return categories.Select(c => new SelectListItem(c.Name, c.Id.ToString()));
        }
    }
}










































//public IActionResult Edit(int id)
//{
//    Contact contact = _contactService.Get(id);
//    if(contact is null)
//        
//    EditContactForm form = new EditContactForm() {
    //    Id = contact.Id;
    //    LastName = contact.LastName;
    //    FirstName = contact.FirstName;
    //    Email = contact.Email;
    //    CategoryId = contact.CategoryId;
    //    Categories = GetCategories();
//    };
//    

//    return View(form);
//}

//[HttpPost]
//public IActionResult Edit(EditContactForm form)
//{
//    if (!ModelState.IsValid)
//    {
//        form.Categories = GetCategories();
//        return View(form);
//    }

//    return RedirectToAction("Index");
//}

WepAppEmpty/Views/Contact/Create.cshtml
@{ 
    ViewBag.Title = "Créer un contact";
    string @title1 = "Créer un contact";
    string @title2 = "Modifier un contact";

}
@model CreateContactForm
@*Ici je définis que mon model est un CreateContactForm*@


    <!--Il s'agit ici du HtmlHelpers qui ne contient que de méthodes d'extension dont le but est d'aider à créer un formulaire-->
    @*<div>
        @Html.ValidationSummary(false)
    </div>
    <div asp-validation-summary="All">
        @Html.ValidationSummary(false)
    </div>*@
    <h2>@if (Model.Id == 0) { @title1 } else { @title2 }</h2>
    <form action="~/Contact/create" method="post">

        <!--<div>
    @Html.DisplayNameFor(m => m.LastName);-->
        @*<label for="LastName">LastName : </label>*@
        <!--@Html.EditorFor(m => m.LastName)-->
        @*<input type="text" name="LastName" value="" />*@
        <!--<div>
            @Html.ValidationMessageFor(m => m.LastName)
        </div>
    </div>-->
        @if (Model.Id != 0)
        {
            <div style="display: none">
                <label asp-for="Id"></label>
                <input asp-for="Id" class="form-control" aria-describedby="inputGroupPrepend3 validationServerUsernameFeedback" readonly />
            </div>
        }
        <div>
            <label asp-for="LastName"></label>
            <input asp-for="LastName" class="form-control" aria-describedby="inputGroupPrepend3 validationServerUsernameFeedback" />
            <div>
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div>
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control" aria-describedby="inputGroupPrepend3 validationServerUsernameFeedback" />
            <div>
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <div>
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control" aria-describedby="inputGroupPrepend3 validationServerUsernameFeedback" />
            <div>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div>
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" asp-items="Model.Categories">
                <!--Model.Categories est l'attribut Categories du formulaire qui est envoyé dans ma méthode create pour afficher le formulaire dans le controller -->
                <option value="0" disabled>Choisir une catégorie</option>
            </select>
            <div>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            @*<div>
            <select name="CategoryId" class="form-control">
                <option value="3">Choisir une catégorie</option>
                <option value="1">Professionnel</option>
                <option value="2">Personnel</option>
            </select>
        </div>*@
        </div>

        <div id="btn">
            @if (Model.Id == 0)
            {<button type="submit" class="btn btn-lg">Nouveau Contact</button> }
            else
            { <button type="submit" class="btn btn-lg">Modifier Contact</button>}
            <a asp-action="Index" asp-controller="Contact" class="btn btn-lg">Annuler</a>
        </div>
    </form>

WepAppEmpty/Views/Contact/Details.cshtml
@model Model.Client.Data.Contact

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Contact</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

WepAppEmpty/Views/Contact/Edit.cshtml
@{
    ViewBag.Title = "Editer un contact";
}
@model EditContactForm
@*Ici je définis que mon model est un CreateContactForm*@


<!--Il s'agit ici du HtmlHelpers qui ne contient que de méthodes d'extension dont le but est d'aider à créer un formulaire-->
<div>
    @Html.ValidationSummary(false)
</div>
<div asp-validation-summary="All">
    @Html.ValidationSummary(false)
</div>
<h2>Modifier un contact</h2>
<form action="~/Contact/Edit" method="post">
    <div style="display: none">
        <label asp-for="Id"></label>
        <input asp-for="Id" class="form-control" aria-describedby="inputGroupPrepend3 validationServerUsernameFeedback" readonly/>
    </div>
    <div>
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" aria-describedby="inputGroupPrepend3 validationServerUsernameFeedback" />
        <div>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
    </div>
    <div>
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" aria-describedby="inputGroupPrepend3 validationServerUsernameFeedback" />
        <div>
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
    </div>
    <div>
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" aria-describedby="inputGroupPrepend3 validationServerUsernameFeedback" />
        <div>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div>
        <label asp-for="CategoryId"></label>
        <select asp-for="CategoryId" asp-items="Model.Categories">
            <!--Model.Categories est l'attribut Categories du formulaire qui est envoyé dans ma méthode create pour afficher le formulaire dans le controller -->
            <option value="0" disabled>Choisir une catégorie</option>
        </select>
        @*<div>
                <select name="CategoryId" class="form-control">
                    <option value="3">Choisir une catégorie</option>
                    <option value="1">Professionnel</option>
                    <option value="2">Personnel</option>
                </select>
            </div>*@
    </div>

    <div id="btn">
        <button type="submit" class="btn btn-lg">Modifier Contact</button>
        <a asp-action="Index" asp-controller="Contact" class="btn btn-lg">Annuler</a>
    </div>
</form>

WepAppEmpty/Views/Contact/Index.cshtml
@model Dictionary<string, IEnumerable<Contact>>

@{
    ViewData["Title"] = "Index";
}

<h1>Liste des contacts</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

@foreach (KeyValuePair<string, IEnumerable<Contact>> kvp in Model)
{
    <h3>@kvp.Key</h3>
    <div id="contact-list">
        @foreach (var value in kvp.Value)
        {
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@value.LastName @value.FirstName</h5>
                    <h6 class="card-subtitle mb-2 text-muted"><span class="title-attr">Nom :</span><span>@value.LastName</span> </h6>
                    <h6 class="card-subtitle mb-2 text-muted"><span class="title-attr">Prénom :</span><span>@value.FirstName</span> </h6>
                    <h6 class="card-subtitle mb-2 text-muted"><span class="title-attr">Email :</span><span>@value.Email</span> </h6>

                    <div>
                        <!--<td>-->@*<a href="~/contact/details/@c.Id">Details</a>*@<!--</td>-->
                        <a class="card-link" asp-action="Details" asp-controller="Contact" asp-area="" asp-route-id="@value.Id">Details</a>
                        <a class="card-link" asp-action="Create" asp-controller="Contact" asp-area="" asp-route-id="@value.Id">Update</a>
                        <a class="card-link" asp-action="Delete" asp-controller="Contact" asp-area="" asp-route-id="@value.Id">Delete</a>
                    </div>
                </div>
            </div>
        }
    </div>
 }