WepAppEmpty/Areas/Admin/Controllers/AllContactsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Model.Client.Data;
using Model.Client.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WepAppEmpty.Areas.Admin.Infracstructures.Security;
using WepAppEmpty.Areas.Admin.Models;
using WepAppEmpty.Infracstructures.Sessions;

namespace WepAppEmpty.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AdminRequired]
    public class AllContactsController : Controller
    {
        private readonly ISessionManager _sessionManager;
        private readonly IContactRepository _contactRepository;
        private readonly ICategoryRepository _categoryRepository;

        public AllContactsController(IContactRepository contactService, ICategoryRepository categoryService, ISessionManager sessionManager)
        {
            _contactRepository = contactService;
            _categoryRepository = categoryService;
            _sessionManager = sessionManager;
        }
        // GET: AllContactsController
        public ActionResult Index()
        {

            AllContacts allContacts = new AllContacts();

            allContacts.Contacts = _contactRepository.Get();

            //Dictionary<Category, List<Contact>> Dictionnary = new Dictionary<Category, List<Contact>>();
            foreach(Category c in _categoryRepository.Get())
            {
                allContacts.Dictionnary.Add(c, _contactRepository.GetByCategory(c.Id).ToList());
            }
            //var Categories = _categoryRepository.Get();
            //var contacts = new AllContacts
            //{
            //    Categories = _categoryRepository.Get(),
            //    Personnels = _contactRepository.GetPersonnalCategory(),
            //    Professionnal = _contactRepository.GetProfessionnalCategory(),
            //    ContactsAll = _contactRepository.Get()
            //};
            //var contacts = _contactRepository.Get();

            return View(allContacts);
        }

        // GET: AllContactsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AllContactsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AllContactsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AllContactsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AllContactsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AllContactsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AllContactsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WepAppEmpty/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Model.Client.Data;
using Model.Client.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WepAppEmpty.Areas.Admin.Infracstructures.Security;
using WepAppEmpty.Areas.Admin.Models;
using WepAppEmpty.Areas.Admin.Models.Forms;

namespace WepAppEmpty.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AdminRequired]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IContactRepository _contactRepository;

        public CategoryController(ICategoryRepository categoryRepository, IContactRepository contactRepository)
        {
            _categoryRepository = categoryRepository;
            _contactRepository = contactRepository;
        }
        public IActionResult Index()
        {
            IEnumerable<DisplayCategory> categories = _categoryRepository.Get().Select(c => new DisplayCategory() { Id = c.Id, Name = c.Name });
            
            return View(categories);
        }

        public IActionResult Create(int Id)
        {
            CreateCategoryForm form = new CreateCategoryForm();
            if(Id != 0)
            {
                Category category = _categoryRepository.Get(Id);
                form.Id = Id;
                form.Name = category.Name;
            } 

            return View(form);
        }

        [HttpPost]
        public IActionResult Create(CreateCategoryForm form)
        {
            if (!ModelState.IsValid)
                return View(form);

            if (form.Id != 0)
            {
                Category category = _categoryRepository.Get(form.Id);
                category.Name = form.Name;

                _categoryRepository.Update(form.Id, category);

            } else
            {
                Category newCategory = new Category(form.Name);

                _categoryRepository.Insert(newCategory);
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            CategoryStatut categoryStatut = new CategoryStatut();

            categoryStatut.category = _categoryRepository.Get(id);

            categoryStatut.ContactsByCategory = _contactRepository.GetByCategory(id);
            
            return View(categoryStatut);
        }
        [HttpPost]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            _categoryRepository.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

WepAppEmpty/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gestion Contact - @ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestion de contacts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil Utilisateurs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AllContacts" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>